### ISSUE TITLE
Functioin to delete a contact

### ISSUE THREAD

**Issue by datorium** [datorium-prog1-10/contacts-with-functions-2022-2023#1]
## Why do we need this function?
To allow user to delete existing contacts

**Comment by datorium** [comment]
@datorium I have created the draft of the code, please have a look and provide some feedback from your side.

**Comment by ItsArturs** [comment]
@ItsArturs  I have created the draft of the code, please have a look and provide some feedback from your side.

**Comment by datorium** [comment]
Hey, great job! But I think we need to use .pop() method in this case.

**Comment by PufSunCat** [comment]
> Hey, great job! But I think we need to use .pop() method in this case.

hi

**Comment by datorium** [comment]
The task is solved, the function allows to delete a contact specified by name only.
